from enum import IntEnum


class ArrowType(IntEnum):
    EMPTY = 0
    ARROW = 1
    SOURCE = 2
    BLOCKER = 3
    DELAY = 4
    DETECTOR = 5
    SPLITTER_UP_DOWN = 6
    SPLITTER_UP_RIGHT = 7
    SPLITTER_UP_RIGHT_LEFT = 8
    IMPULSE = 9
    BLUE_ARROW = 10
    DIAGONAL_ARROW = 11
    SPLITTER_UP_UP = 12
    SPLITTER_RIGHT_UP = 13
    SPLITTER_UP_DIAGONAL = 14
    LOGIC_NOT = 15
    LOGIC_AND = 16
    LOGIC_XOR = 17
    LATCH = 18
    FLIP_FLOP = 19
    RANDOM = 20
    BUTTON = 21
    LEVEL_SOURCE = 22
    LEVEL_TARGET = 23
    DIRECTIONAL_BUTTON = 24
    WALL = 25
